#!/usr/bin/env python3
"""Download the latin subsets of the three font families and emit styles/fonts.css.

    python scripts/fetch-fonts.py

Inter and JetBrains Mono are variable fonts — Google returns one identical file
for every weight requested. This script writes them out per weight; afterwards,
deduplicate by checksum and collapse each family to a single @font-face with a
weight RANGE, which is what the committed styles/fonts.css does. That step
halved the font payload from 245 KB to 120 KB.

Only the `latin` subset is kept. latin-ext, cyrillic, greek and vietnamese are
dropped deliberately: the site is English and French, and every French accented
character lives in the latin subset.

Re-run only when changing families, weights or subsets.
"""

import os
import re
import sys
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_DIR = os.path.join(ROOT, "fonts")
CSS_OUT = os.path.join(ROOT, "styles", "fonts.generated.css")

GF_URL = (
    "https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1"
    "&family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap"
)

# Google serves different @font-face blocks by User-Agent; a modern browser UA
# gets woff2, which is what we want.
UA = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    )
}


def main():
    req = urllib.request.Request(GF_URL, headers=UA)
    with urllib.request.urlopen(req, timeout=30) as r:
        css = r.read().decode("utf-8")

    blocks = re.findall(r"/\*\s*([a-z0-9-]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S)
    print("total @font-face blocks served:", len(blocks))

    os.makedirs(FONT_DIR, exist_ok=True)
    kept = []

    for subset, block in blocks:
        if subset != "latin":
            continue
        fam = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        style = re.search(r"font-style:\s*(\w+)", block).group(1)
        weight = re.search(r"font-weight:\s*(\d+)", block).group(1)
        url = re.search(r"url\(([^)]+)\)", block).group(1)
        urange = re.search(r"unicode-range:\s*([^;]+);", block)

        slug = fam.lower().replace(" ", "-")
        fname = f"{slug}-{weight}-{style}.woff2"

        with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=30) as r:
            data = r.read()
        with open(os.path.join(FONT_DIR, fname), "wb") as f:
            f.write(data)

        kept.append({
            "fam": fam, "style": style, "weight": weight, "file": fname,
            "size": len(data), "urange": urange.group(1).strip() if urange else None,
        })
        print(f"  {fname:42} {len(data):>7,} bytes")

    total = sum(k["size"] for k in kept)
    print(f"\n{len(kept)} files, {total:,} bytes ({total / 1024:.0f} KB)")

    lines = [
        "/* GENERATED by scripts/fetch-fonts.py — for reference only.",
        " * The committed stylesheet is styles/fonts.css, which collapses the",
        " * variable families to one file each with a weight range.",
        " */",
        "",
    ]
    for k in kept:
        lines += [
            "@font-face {",
            f"    font-family: '{k['fam']}';",
            f"    font-style: {k['style']};",
            f"    font-weight: {k['weight']};",
            "    font-display: swap;",
            f"    src: url('/fonts/{k['file']}') format('woff2');",
        ]
        if k["urange"]:
            lines.append(f"    unicode-range: {k['urange']};")
        lines += ["}", ""]

    with open(CSS_OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print("wrote styles/fonts.generated.css")
    print("\nNext: dedupe by checksum (md5sum fonts/*.woff2), then fold duplicates")
    print("into a single @font-face with a weight range in styles/fonts.css.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
